### PR TITLE
Add an RFC/Bind parser module

### LINKED ISSUE #10: Accept RFC-compliant zonefile
The current zonefile accepted by this script technically isn't a zonefile, its a list of API commands.

It would be useful to accept a bind-style / RFC 1035 formatted zonefile.  These can be downloaded from mythic beasts to pre-seed a domain's zone in the top-right menu of the DNS editing page, and can be parsed / verified by the python `dnszone` package

We currently use a sed script to turn these into list of API commands to feed to dns-zone-sync.  This collapses whitespace into a single space (limitation of the API), adds `ADD` to the beginning of the line, and removes the `$ORIGIN` line.

```
sed -e 's/ \+/ /g' -e 's/^/ADD /' -e '/$ORIGIN/d' zone.file
```

### PR DESCRIPTION
**Pull request by nowster**
Closes #10

### CODE REVIEW

**Comment by nowster** [comment]
Merge #17 first.

**Comment by pwaring** [comment]
This looks good, I'm going to push a new release in 0.9.x to incorporate the previous changes and then test to make sure that this PR works with both formats as I've got 20+ domains with different records. Once I've done that I'll get this merged and then make a 1.x release as it's a big change in functionality.

**Comment by nowster** [comment]
The idea of the extra option is not to break existing scripts.

**Comment by pwaring** [comment]
Holding fire on this as a previous PR seems to have introduced a bug for the original 'list of commands' zone file format (#19)

**Pull request merged**
